### ISSUE TITLE
Adding the client to the miner repo

### ISSUE THREAD

**Issue by enniome** [bazo-blockchain/bazo-miner#15]
Hi everyone 👋😊

@tbocek, @marcosteiner and I discussed if adding the client to the bazo-miner repo would make any sense. Our thoughts were that we could better test the integration of the virtual machine and the execution of smart contracts. At first glance, no disadvantages occurred to us. Any points we didn't think of?

Cheers 😎

**Comment by mchetelat** [comment]
Hi. @enniome: Can you give more detail information, how the integration would look like? Cheers

**Comment by enniome** [comment]
We discussed this today, @tbocek will have a deeper look.
